<?php
class KelasSeeder extends Seeder{
  public function run(){
    DB::table('kelas')->delete();

    $data=array(
      array(
        'kd_kelas'=>'7.A',
        'kelas'=>'7',
        'subkelas'=>'A'
      ),
      array(
        'kd_kelas'=>'7.B',
        'kelas'=>'7',
        'subkelas'=>'B'
      ),
      array(
        'kd_kelas'=>'7.C',
        'kelas'=>'7',
        'subkelas'=>'C'
      ),
      array(
        'kd_kelas'=>'7.D',
        'kelas'=>'7',
        'subkelas'=>'D'
      ),
      array(
        'kd_kelas'=>'7.E',
        'kelas'=>'7',
        'subkelas'=>'D'
      ),
      array(
        'kd_kelas'=>'7.F',
        'kelas'=>'7',
        'subkelas'=>'F'
      ),
      array(
        'kd_kelas'=>'7.G',
        'kelas'=>'7',
        'subkelas'=>'G'
      ),

      //kelas 8
      array(
        'kd_kelas'=>'8.A',
        'kelas'=>'8',
        'subkelas'=>'A'
      ),
      array(
        'kd_kelas'=>'8.B',
        'kelas'=>'8',
        'subkelas'=>'B'
      ),
      array(
        'kd_kelas'=>'8.C',
        'kelas'=>'8',
        'subkelas'=>'C'
      ),
      array(
        'kd_kelas'=>'8.D',
        'kelas'=>'8',
        'subkelas'=>'D'
      ),
      array(
        'kd_kelas'=>'8.E',
        'kelas'=>'8',
        'subkelas'=>'E'
      ),
      array(
        'kd_kelas'=>'8.F',
        'kelas'=>'8',
        'subkelas'=>'F'
      ),
      array(
        'kd_kelas'=>'8.G',
        'kelas'=>'8',
        'subkelas'=>'G'
      ),
      array(
        'kd_kelas'=>'8.H',
        'kelas'=>'8',
        'subkelas'=>'H'
      ),

      //kelas 9
      array(
        'kd_kelas'=>'9.A',
        'kelas'=>'9',
        'subkelas'=>'A'
      ),
      array(
        'kd_kelas'=>'9.B',
        'kelas'=>'9',
        'subkelas'=>'B'
      ),
      array(
        'kd_kelas'=>'9.C',
        'kelas'=>'9',
        'subkelas'=>'C'
      ),
      array(
        'kd_kelas'=>'9.D',
        'kelas'=>'9',
        'subkelas'=>'D'
      ),
      array(
        'kd_kelas'=>'9.E',
        'kelas'=>'9',
        'subkelas'=>'E'
      ),
      array(
        'kd_kelas'=>'9.F',
        'kelas'=>'9',
        'subkelas'=>'F'
      ),
      array(
        'kd_kelas'=>'9.G',
        'kelas'=>'9',
        'subkelas'=>'G'
      ),
      array(
        'kd_kelas'=>'9.H',
        'kelas'=>'9',
        'subkelas'=>'H'
      )
    );

    DB::table('kelas')->insert($data);
  }
}
